### ISSUE TITLE
add azimuth for second component to azimuth report

### ISSUE THREAD

**Issue by crotwell** [usgs/asl-sensor-suite#102]
The azimut report gives the best fit azimuth of the "1" component relative to the reference "north" and plots the second component on the plot, but doesn't give its azimuth. I know I can just add, or maybe is it subtract, 90 deg. See I am already confused. Would be nice to print this value as well just to keep people like me from accidentally doing the wrong thing.

**Comment by crotwell** [comment]
Also nice to include the offset value / reference sensor azimuth in the report.

**Comment by amkearns-usgs** [comment]
I have added an additional line on the angle plot to give the precise angle of the east-facing sensor. I would like to be more precise that the value being added to the fit angle is the user-specified offset, but the text region would be likely to overlap with the text specifying angle ticks on the actual plot. 

As a compromise, the offset angle will not be displayed if it is zero, and the generated PDF reports will explicitly restate the value of the reference angle after all other text generated from the experiment.

Change is added to the test build with the most recent commits (dcfd59acfed0f9287db59332e915d0ccfeed6fb8, 494ec719da2788938539feaad7e3f9fb141c961a). These will be integrated into a major release on the main branch after work-in-progress on updating and augmenting the generic hardware response set embedded in the program is completed.
